# Generated by Django 5.0.1 on 2025-02-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuotexCallbackData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(max_length=255, verbose_name="ID do Evento"),
                ),
                (
                    "click_id",
                    models.CharField(max_length=255, verbose_name="ID do Click"),
                ),
                (
                    "site_id",
                    models.CharField(max_length=255, verbose_name="ID do Site"),
                ),
                (
                    "link_id",
                    models.CharField(max_length=255, verbose_name="ID do Link"),
                ),
                (
                    "trader_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="ID do Trader"
                    ),
                ),
                (
                    "payout",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valor do Depósito",
                    ),
                ),
                ("status", models.CharField(max_length=255, verbose_name="Status")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
            ],
        ),
    ]
