# Generated by Django 5.0.1 on 2025-02-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("callback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotexcallbackdata",
            name="click_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID do Click"
            ),
        ),
        migrations.AlterField(
            model_name="quotexcallbackdata",
            name="event_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID do Evento"
            ),
        ),
        migrations.AlterField(
            model_name="quotexcallbackdata",
            name="link_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID do Link"
            ),
        ),
        migrations.AlterField(
            model_name="quotexcallbackdata",
            name="payout",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor do Depósito",
            ),
        ),
        migrations.AlterField(
            model_name="quotexcallbackdata",
            name="site_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID do Site"
            ),
        ),
        migrations.AlterField(
            model_name="quotexcallbackdata",
            name="status",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Status"
            ),
        ),
    ]
