# Generated by Django 5.0.1 on 2025-02-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("callback", "0002_alter_quotexcallbackdata_click_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotexcallbackdata",
            name="release_without_validation",
            field=models.BooleanField(
                default=False,
                help_text="Esta flag é para poder liberar o acesso ao usuario sem precisar validar o link de onde ele veio",
                verbose_name="Liebrar sen validação do ID do link",
            ),
        ),
    ]
