# Generated by Django 5.1.2 on 2024-10-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_charisma',
        ),
        migrations.AddField(
            model_name='user',
            name='user_system',
            field=models.BooleanField(default=False, help_text='Usuário funcionário da plataforma.', verbose_name='Usuário do sistema'),
        ),
    ]
