# Generated by Django 5.1.2 on 2024-11-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_user_charisma_user_user_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Indica se o usuário aceitou os termos de uso.', verbose_name='Aceite dos Termos'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_text',
            field=models.TextField(default='Termos de uso: [conteúdo padrão]', editable=False, verbose_name='Texto dos Termos de Uso'),
        ),
    ]
