# Generated by Django 5.1.2 on 2025-01-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_terms_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encrypted_password',
            field=models.BinaryField(blank=True, help_text='Senha encriptografada do usuário', null=True),
        ),
    ]
