# Generated by Django 5.1.2 on 2025-01-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_password_primary_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='encrypted_password',
            field=models.BinaryField(blank=True, editable=True, help_text='Senha encriptografada do usuário', null=True),
        ),
    ]
