# Generated by Django 5.0.1 on 2025-01-26 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="ID da Conta")),
                (
                    "order_type",
                    models.CharField(
                        choices=[("BUY", "Compra"), ("SELL", "Venda")],
                        max_length=10,
                        verbose_name="Tipo de Ordem",
                    ),
                ),
                (
                    "order_result_status",
                    models.CharField(
                        choices=[
                            ("WIN", "VITÓRIA"),
                            ("LOSS", "PERCA"),
                            ("DOGI", "EMPATE"),
                        ],
                        max_length=10,
                        verbose_name="Status do resultado",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor da Ordem"
                    ),
                ),
                (
                    "result",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Resultado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Criação"
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Execução"
                    ),
                ),
                (
                    "request_body",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Dados recebidos"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("EXECUTED", "Executada"),
                            ("FAILED", "Falha"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Tipo de Corretora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de Trade",
                "verbose_name_plural": "Ordens de Trade",
                "ordering": ["-created_at"],
            },
        ),
    ]
