# Generated by Django 5.0.1 on 2025-01-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradeorder",
            name="close_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Horário de Fechamento"
            ),
        ),
        migrations.AddField(
            model_name="tradeorder",
            name="id_trade",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="ID da Operação na Corretora",
            ),
        ),
        migrations.AddField(
            model_name="tradeorder",
            name="open_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Horário de Abertura"
            ),
        ),
        migrations.AddField(
            model_name="tradeorder",
            name="percent_profit",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Percentual de Lucro"
            ),
        ),
        migrations.AddField(
            model_name="tradeorder",
            name="request_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="ID da Requisição"
            ),
        ),
        migrations.AddField(
            model_name="tradeorder",
            name="uid",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="UID do Usuário na Corretora"
            ),
        ),
        migrations.AlterField(
            model_name="tradeorder",
            name="order_result_status",
            field=models.CharField(
                choices=[
                    ("WIN", "VITÓRIA"),
                    ("LOSS", "PERCA"),
                    ("DOGI", "EMPATE"),
                    ("PENDING", "PENDENTE"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="Status do resultado",
            ),
        ),
    ]
