# Generated by Django 5.0.1 on 2025-01-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0002_tradeorder_close_time_tradeorder_id_trade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradeorder",
            name="asset_order",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Par de moeda"
            ),
        ),
    ]
