# Generated by Django 5.0.1 on 2025-02-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0003_tradeorder_asset_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradeorder",
            name="is_active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Ativo"
            ),
        ),
    ]
