# Generated by Django 5.0.1 on 2025-02-02 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0008_quotexmanagement_management_type"),
        ("trading", "0004_tradeorder_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tradeorder",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="tradeorder",
            name="object_id",
        ),
        migrations.AddField(
            model_name="tradeorder",
            name="broker",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to="integrations.quotex",
                verbose_name="Corretora",
            ),
            preserve_default=False,
        ),
    ]
