# Generated by Django 5.0.1 on 2025-01-26 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_alter_deposit_customer"),
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotexManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stop_gain",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor máximo para ganho antes de parar.",
                        max_digits=10,
                        verbose_name="Stop Gain",
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor máximo para perda antes de parar.",
                        max_digits=10,
                        verbose_name="Stop Loss",
                    ),
                ),
                (
                    "stop_loss_type",
                    models.CharField(
                        choices=[
                            ("MODERADO", "Moderado"),
                            ("AGRESSIVO", "Agressivo"),
                            ("SNIPER", "Sniper"),
                        ],
                        default="MODERADO",
                        max_length=10,
                        verbose_name="Tipo de Stop Loss",
                    ),
                ),
                (
                    "entry_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor inicial para cada operação.",
                        max_digits=10,
                        verbose_name="Valor de Entrada",
                    ),
                ),
                (
                    "trend_filter",
                    models.BooleanField(
                        default=True,
                        help_text="Ativar ou desativar o filtro de tendência.",
                        verbose_name="Filtro de Tendência",
                    ),
                ),
                (
                    "martingale",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número máximo de martingales permitidos.",
                        verbose_name="Martingale",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotex_management",
                        to="customer.customer",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gerenciamento Quotex",
                "verbose_name_plural": "Gerenciamento Quotex",
                "ordering": ["-created_at"],
            },
        ),
    ]
