# Generated by Django 5.0.1 on 2025-01-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_quotexmanagement_factor_martingale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotex",
            name="is_bot_active",
            field=models.BooleanField(default=False, verbose_name="Robô Ativo"),
        ),
    ]
