# Generated by Django 5.0.1 on 2025-01-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_quotex_is_bot_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotex",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Aqui é para poder verificar se esta corretora estará ativa para o cliente ou não",
                verbose_name="Ativo para Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="quotex",
            name="is_bot_active",
            field=models.BooleanField(
                default=False,
                help_text="Está opção é para ativar o robô para está corretora ou desativar.",
                verbose_name="Robô Ativo",
            ),
        ),
    ]
