# Generated by Django 5.0.1 on 2025-01-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0005_alter_quotex_is_active_alter_quotex_is_bot_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotex",
            name="currency_symbol",
            field=models.EmailField(
                blank=True, max_length=10, null=True, verbose_name="Simbolo R$/US"
            ),
        ),
    ]
