# Generated by Django 5.0.1 on 2025-01-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0006_quotex_currency_symbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotex",
            name="currency_symbol",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Simbolo R$/US"
            ),
        ),
    ]
