# Generated by Django 5.0.1 on 2025-01-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0007_alter_quotex_currency_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotexmanagement",
            name="management_type",
            field=models.CharField(
                choices=[
                    ("CONSERVADOR", "Conservador"),
                    ("MODERADO", "Moderado"),
                    ("ALAVANCAGEM", "Alavancagem"),
                    ("PERSONALIZADO", "Personalizado"),
                ],
                default="PERSONALIZADO",
                max_length=15,
                verbose_name="Tipo de Gerenciamento",
            ),
        ),
    ]
