# Generated by Django 5.0.1 on 2025-02-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0008_quotexmanagement_management_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotexmanagement",
            name="factor_martingale",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Valor multiplicador dos martingales permitidos.",
                verbose_name="Fator Multiplicador Martingale",
            ),
        ),
        migrations.AlterField(
            model_name="quotexmanagement",
            name="martingale",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Número máximo de martingales permitidos.",
                verbose_name="Martingale",
            ),
        ),
    ]
