PARITIES = [
    'AUDCAD',
    'AUDCHF',
    'AUDJPY',
    'AUDUSD',
    'CADCHF',
    'CADJPY',
    'EURAUD',
    'EURCAD',
    'EURCHF',
    'EURJPY',
    'EURGBP',
    'EURUSD',
    'GBPAUD',
    'GBPCAD',
    'GBPCHF',
    'GBPJPY',
    'GBPUSD',
    'NZDCAD',
    'NZDUSD',
    'USDCAD',
    'USDCHF',
    'USDJPY'
]

CUSTOM_PARITIES = {
    'AUDCAD': '🇦🇺🇨🇦 AUD/CAD',
    'AUDCHF': '🇦🇺🇨🇭 AUD/CHF',
    'AUDJPY': '🇦🇺🇯🇵 AUD/JPY',
    'AUDNZD': '🇦🇺🇳🇿 AUD/NZD',
    'AUDUSD': '🇦🇺🇺🇸 AUD/USD',
    'CADCHF': '🇨🇦🇨🇭 CAD/CHF',
    'CADJPY': '🇨🇦🇯🇵 CAD/JPY',
    'CHFJPY': '🇨🇭🇯🇵 CHF/JPY',
    'EURAUD': '🇪🇺🇦🇺 EUR/AUD',
    'EURCAD': '🇪🇺🇨🇦 EUR/CAD',
    'EURCHF': '🇪🇺🇨🇭 EUR/CHF',
    'EURGBP': '🇪🇺🇬🇧 EUR/GBP',
    'EURJPY': '🇪🇺🇯🇵 EUR/JPY',
    'EURUSD': '🇪🇺🇺🇸 EUR/USD',
    'GBPAUD': '🇬🇧🇦🇺 GBP/AUD',
    'GBPCAD': '🇬🇧🇨🇦 GBP/CAD',
    'GBPCHF': '🇬🇧🇨🇭 GBP/CHF',
    'GBPJPY': '🇬🇧🇯🇵 GBP/JPY',
    'GBPNZD': '🇬🇧🇳🇿 GBP/NZD',
    'GBPUSD': '🇬🇧🇺🇸 GBP/USD',
    'NZDCAD': '🇳🇿🇨🇦 NZD/CAD',
    'NZDJPY': '🇳🇿🇯🇵 NZD/JPY',
    'NZDUSD': '🇳🇿🇺🇸 NZD/USD',
    'USDCAD': '🇺🇸🇨🇦 USD/CAD',
    'USDCHF': '🇺🇸🇨🇭 USD/CHF',
    'USDJPY': '🇺🇸🇯🇵 USD/JPY'
}
