# Generated by Django 5.0.1 on 2025-02-05 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('type', models.CharField(choices=[('insuficient_amount', 'Saldo insuficiente'), ('login_error', 'Erro no login'), ('credentials_error', 'Erro nas credenciais'), ('expire_trial', 'Período de teste expirado'), ('access_interrupted', 'Acesso interrompido')], default='insuficient_amount', max_length=50, verbose_name='Tipo')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('html_content', models.TextField(blank=True, help_text='Conteúdo HTML que pode ser renderizado na tela', null=True, verbose_name='HTML Personalizado')),
                ('url_redirect', models.URLField(blank=True, null=True, verbose_name='URL de Redirecionamento')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação Base',
                'verbose_name_plural': 'Notificações Base',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='StopGainLossNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('type', models.CharField(choices=[('stop_loss', 'Stop Loss'), ('stop_gain', 'Stop Gain')], default='stop_loss', max_length=50, verbose_name='Tipo')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('html_content', models.TextField(blank=True, help_text='Conteúdo HTML que pode ser renderizado na tela', null=True, verbose_name='HTML Personalizado')),
                ('url_redirect', models.URLField(blank=True, null=True, verbose_name='URL de Redirecionamento')),
                ('gain_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor alcançado em caso de Stop Gain', max_digits=10, null=True, verbose_name='Valor de Ganho')),
                ('loss_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor alcançado em caso de Stop Loss', max_digits=10, null=True, verbose_name='Valor de Perda')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação de Stop',
                'verbose_name_plural': 'Notificações de Stop',
                'ordering': ['-created_date'],
            },
        ),
    ]
