# Generated by Django 5.0.1 on 2025-01-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_alter_deposit_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="avatar",
            field=models.URLField(blank=True, null=True, verbose_name="Avatar"),
        ),
        migrations.AddField(
            model_name="customer",
            name="country",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="País"
            ),
        ),
    ]
