# Generated by Django 5.0.1 on 2025-02-01 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_customer_avatar_customer_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="username",
        ),
    ]
