# Generated by Django 5.0.1 on 2025-02-01 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_remove_customer_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customer",
            managers=[],
        ),
    ]
