# Generated by Django 5.0.1 on 2025-02-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_alter_customer_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="backup_password",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Senha backup"
            ),
        ),
    ]
